export  const brandNames = [
    "Land Rover",
    "Maserati",
    "Subaru",
    "Bugatti",
    "Honda",
    "Nissan",
    "Ford",
    "Fiat",
    "Jeep",
    "Volkswagen",
    "Jaguar",
    "Audi",
    "Toyota",
    "Lamborghini",
    "Lexus",
    "Porsche",
    "Bentley",
    "BMW",
    "Benz",
    "Hyundai",
]